// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"go.opentelemetry.io/collector/confmap"
	"go.opentelemetry.io/collector/filter"
)

// MetricConfig provides common config for a particular metric.
type MetricConfig struct {
	Enabled bool `mapstructure:"enabled"`

	enabledSetByUser bool
}

func (ms *MetricConfig) Unmarshal(parser *confmap.Conf) error {
	if parser == nil {
		return nil
	}
	err := parser.Unmarshal(ms)
	if err != nil {
		return err
	}
	ms.enabledSetByUser = parser.IsSet("enabled")
	return nil
}

// MetricsConfig provides config for hostmetricsreceiver/groupprocess metrics.
type MetricsConfig struct {
	GroupProcessCount               MetricConfig `mapstructure:"group.process.count"`
	GroupProcessCPUPercent          MetricConfig `mapstructure:"group.process.cpu.percent"`
	GroupProcessMemoryPercent       MetricConfig `mapstructure:"group.process.memory.percent"`
	GroupProcessOpenFileDescriptors MetricConfig `mapstructure:"group.process.open_file_descriptors"`
	GroupProcessThreads             MetricConfig `mapstructure:"group.process.threads"`
}

func DefaultMetricsConfig() MetricsConfig {
	return MetricsConfig{
		GroupProcessCount: MetricConfig{
			Enabled: true,
		},
		GroupProcessCPUPercent: MetricConfig{
			Enabled: true,
		},
		GroupProcessMemoryPercent: MetricConfig{
			Enabled: true,
		},
		GroupProcessOpenFileDescriptors: MetricConfig{
			Enabled: true,
		},
		GroupProcessThreads: MetricConfig{
			Enabled: true,
		},
	}
}

// ResourceAttributeConfig provides common config for a particular resource attribute.
type ResourceAttributeConfig struct {
	Enabled bool `mapstructure:"enabled"`
	// Experimental: MetricsInclude defines a list of filters for attribute values.
	// If the list is not empty, only metrics with matching resource attribute values will be emitted.
	MetricsInclude []filter.Config `mapstructure:"metrics_include"`
	// Experimental: MetricsExclude defines a list of filters for attribute values.
	// If the list is not empty, metrics with matching resource attribute values will not be emitted.
	// MetricsInclude has higher priority than MetricsExclude.
	MetricsExclude []filter.Config `mapstructure:"metrics_exclude"`

	enabledSetByUser bool
}

func (rac *ResourceAttributeConfig) Unmarshal(parser *confmap.Conf) error {
	if parser == nil {
		return nil
	}
	err := parser.Unmarshal(rac)
	if err != nil {
		return err
	}
	rac.enabledSetByUser = parser.IsSet("enabled")
	return nil
}

// ResourceAttributesConfig provides config for hostmetricsreceiver/groupprocess resource attributes.
type ResourceAttributesConfig struct {
	GroupName ResourceAttributeConfig `mapstructure:"group.name"`
}

func DefaultResourceAttributesConfig() ResourceAttributesConfig {
	return ResourceAttributesConfig{
		GroupName: ResourceAttributeConfig{
			Enabled: true,
		},
	}
}

// MetricsBuilderConfig is a configuration for hostmetricsreceiver/groupprocess metrics builder.
type MetricsBuilderConfig struct {
	Metrics            MetricsConfig            `mapstructure:"metrics"`
	ResourceAttributes ResourceAttributesConfig `mapstructure:"resource_attributes"`
}

func DefaultMetricsBuilderConfig() MetricsBuilderConfig {
	return MetricsBuilderConfig{
		Metrics:            DefaultMetricsConfig(),
		ResourceAttributes: DefaultResourceAttributesConfig(),
	}
}
