# One of 'breaking', 'deprecation', 'new_component', 'enhancement', 'bug_fix'
change_type: bug_fix

# The name of the component, or a single word describing the area of concern, (e.g. filelogreceiver)
component: routingprocessor

# A brief description of the change.  Surround your text with quotes ("") if it needs to start with a backtick (`).
note: Fix bug in routing processor that prevented collector from starting if `from_attribute` is not provided with `OTTL` routing statements.

# One or more tracking issues related to the change
issues: [16555]

# (Optional) One or more lines of additional information to render under the primary note.
# These lines will be padded with 2 spaces and then inserted directly into the document.
# Use pipe (|) for multiline entries.
subtext:
